//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanWithUs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoanWithUs.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار پشتیبان ناکافی می باشد.
        /// </summary>
        public static string ApplicantLoanRequestInsufficientSupporterCredit {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestInsufficientSupporterCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقاضای شما از سقف مجاز جهت دریافت وام بیشتر است..
        /// </summary>
        public static string ApplicantLoanRequestInvalidAmount {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شما در دست بررسی می باشد، پس از تایید مدیر سامانه امکان تقاضای وام برای شما وجود دارد..
        /// </summary>
        public static string ApplicantLoanRequestNotConfirmedInfo {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestNotConfirmedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اقساط انتخابی صحیح نیست.
        /// </summary>
        public static string ApplicantLoanRequestWithInvalidInstallment {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestWithInvalidInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواستگر گرامی شما در حال حاضر وام تسویه نشده دارید پس از تسویه وام فعلی امکان دریافت وام دارید..
        /// </summary>
        public static string ApplicantLoanRequestWithOpenLoan {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestWithOpenLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواستگر گرامی شما در حال حاضر امکان ثبت درخواست جدید برای شما وجود ندارد.
        /// </summary>
        public static string ApplicantLoanRequestWithOpenRequest {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestWithOpenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما نامعتبر است.
        /// </summary>
        public static string LoanRequestInvalidStateChange {
            get {
                return ResourceManager.GetString("LoanRequestInvalidStateChange", resourceCulture);
            }
        }
    }
}
