//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanWithUs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoanWithUs.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما توسط ادمین سامانه تایید شد و وام شما در صف پرداخت قرار گرفت.
        /// </summary>
        public static string AdminAcceptLoanRequest {
            get {
                return ResourceManager.GetString("AdminAcceptLoanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواستگر گرامی، وام شما با مبلغ {0} پرداخت شد، خواهشمند است در پرداخت به موقع کوشا باشید.
        /// </summary>
        public static string AdminPaidLoanRequest {
            get {
                return ResourceManager.GetString("AdminPaidLoanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما لغو شد.
        /// </summary>
        public static string ApplicantCancelTheRequest {
            get {
                return ResourceManager.GetString("ApplicantCancelTheRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حالی که شما در نردبان {0} قرار دارید اما پشتیبان شما اعتبار کافی جهت پشتیبانی را ندارد.
        /// </summary>
        public static string ApplicantLadderInsufficientSupporterCredit {
            get {
                return ResourceManager.GetString("ApplicantLadderInsufficientSupporterCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار پشتیبان ناکافی می باشد.
        /// </summary>
        public static string ApplicantLoanRequestInsufficientSupporterCredit {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestInsufficientSupporterCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقاضای شما از سقف مجاز جهت دریافت وام بیشتر است..
        /// </summary>
        public static string ApplicantLoanRequestInvalidAmount {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شما در دست بررسی می باشد، پس از تایید مدیر سامانه امکان تقاضای وام برای شما وجود دارد..
        /// </summary>
        public static string ApplicantLoanRequestNotConfirmedInfo {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestNotConfirmedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم تایید ادمین.
        /// </summary>
        public static string ApplicantLoanRequestState_AdminRejected {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestState_AdminRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت شده.
        /// </summary>
        public static string ApplicantLoanRequestState_ApplicantRequested {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestState_ApplicantRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنسل شده.
        /// </summary>
        public static string ApplicantLoanRequestState_Canceled {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestState_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت شده.
        /// </summary>
        public static string ApplicantLoanRequestState_Paied {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestState_Paied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صف پرداخت.
        /// </summary>
        public static string ApplicantLoanRequestState_ReadyToPay {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestState_ReadyToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید پشتیبان.
        /// </summary>
        public static string ApplicantLoanRequestState_SupporterAccepted {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestState_SupporterAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم تایید پشتیبان.
        /// </summary>
        public static string ApplicantLoanRequestState_SupporterRejected {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestState_SupporterRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اقساط انتخابی صحیح نیست.
        /// </summary>
        public static string ApplicantLoanRequestWithInvalidInstallment {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestWithInvalidInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواستگر گرامی شما در حال حاضر وام تسویه نشده دارید پس از تسویه وام فعلی امکان دریافت وام دارید..
        /// </summary>
        public static string ApplicantLoanRequestWithOpenLoan {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestWithOpenLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواستگر گرامی شما در حال حاضر امکان ثبت درخواست جدید برای شما وجود ندارد.
        /// </summary>
        public static string ApplicantLoanRequestWithOpenRequest {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestWithOpenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواستگر گرامی پس از تایید پروفایل کاربری امکان درخواست وام برای شما فراهم می باشد..
        /// </summary>
        public static string ApplicantLoanRequestWithoutTotalConfirmation {
            get {
                return ResourceManager.GetString("ApplicantLoanRequestWithoutTotalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر اطلاعات پس از تایید اطلاعات شما توسط مدیر سامانه وجود ندارد، در صورت نیاز به تغییر درخواست بروزرسانی اطلاعات را بدهید..
        /// </summary>
        public static string ExceptionOnUpdateConfirmedApplicant {
            get {
                return ResourceManager.GetString("ExceptionOnUpdateConfirmedApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما نامعتبر است.
        /// </summary>
        public static string LoanRequestInvalidStateChange {
            get {
                return ResourceManager.GetString("LoanRequestInvalidStateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبان گرامی اعتبار شما جهت تایید این درخواست وام کافی نیست..
        /// </summary>
        public static string SupporterInsufficientAmountToConfirmRequest {
            get {
                return ResourceManager.GetString("SupporterInsufficientAmountToConfirmRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبان گرامی شما دسترسی به اطلاعات این درخواستگر را ندارید.
        /// </summary>
        public static string SupporterNotAllowedForThisApplicant {
            get {
                return ResourceManager.GetString("SupporterNotAllowedForThisApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبان گرامی شما به درخواستگر مذکور دسترسی ندارید..
        /// </summary>
        public static string SupporterNotAllowedToViewApplicant {
            get {
                return ResourceManager.GetString("SupporterNotAllowedToViewApplicant", resourceCulture);
            }
        }
    }
}
